### ISSUE TITLE
Travis CI tests failing for about a year

### ISSUE THREAD

**Issue by msabramo** [Kotti/kotti_navigation#16]
From https://travis-ci.org/Kotti/kotti_navigation/builds:

![screen shot 2015-02-10 at 8 28 52 am](https://cloud.githubusercontent.com/assets/305268/6131181/f5400e26-b0fe-11e4-866c-a174ac268193.png)

**Comment by j23d** [comment]
With the latest changes in the branch [`switch_to_kotti_settings`](https://github.com/Kotti/kotti_navigation/tree/switch_to_kotti_settings) the tests on travis passing again. This branch will be merged to master.
