### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/kotti_navigation#32]
The latest stable version (0.3.1) does not work with newer Kotti versions where there's *not found view* added. It looks this was fixed in master (by adding `and root in lineage_items` at https://github.com/Kotti/kotti_navigation/blob/534e0d57ada85f095954dd79c57a96804b207b4a/kotti_navigation/views.py#L182).
Could we please have a stable release with this fix?

**Comment by j23d** [comment]
Thanks for the reminder that a new release is necessary, lost sight of it. As there are massive changes for the 0.5 version I have to have a closer look before releasing, but it will happen in the next days.

**Comment by piotr-dobrogost** [comment]
It looks like version 0.5 was not tagged.

**Comment by j23d** [comment]
Was tagged, but forgot to push the tag.
